name: vcr
description: A package to mock requests in tests, storing request in json files and reusing
version: 0.1.2
homepage: https://github.com/keviinlouis/vcr

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 

dev_dependencies:
  flutter_test:
    sdk: flutter
